server:
  servlet:
    application-display-name: config-server
  port: 8071
#  port: 8081
   
spring:
  application:
    name: CONFIG-SERVER-EXAMPLE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/com-datou/config-file-example
          default-label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5     
    lease-expiration-duration-in-seconds: 15
management:
  endpoints:
    web:
      exposure:
        include: "*"