server:
  servlet:
    application-display-name: config-server
    context-path: /config/
  port: 8081
spring:
  application:
    name: config-server-example

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
